spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/mytest_db?serverTimezone=Asia/Seoul
    username: test
    password: test1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    org.hibernate: DEBUG